#' Calculating ES score of each geneset.
#'
#' @param  expressionProfile Expression profile with row as genes, column as samples.
#' @param  signatureList Multiple signature gene sets to be enriched.
#'
#' @return

CustomizedssGSEA <- function(expressionProfile, signatureList) {
  # （1）Data preparation
  exp.n <- ncol(expressionProfile)
  exp.m <- nrow(expressionProfile)
  # get the superimposed matrix
  superposition.rank.exp <- superpositionRank(raw.matrix = expressionProfile, m = exp.m, n = exp.n)
  # get rank by column of matrix 'expressionProfile'
  exp.rank <- rankMatrixByCol(superposition.rank = superposition.rank.exp, m = exp.m, n = exp.n)

  # （2）perform ssGSEA
  ssGSEA.score <- sapply(signatureList, function(signatureSet) {
    t1 <- numeric(exp.m)
    gSetIdx <- which(rownames(expressionProfile) %in% signatureSet)
    t1[gSetIdx] <- 1
    geneSet.position <- matrix(rep(t1, times = exp.n), ncol = exp.n)

    # （3）With the rank of all values in the matrix(superposition.rank),
    # get the matrix consist with 0 and 1, indicated the position of geneset
    indicatorInsideGeneSet.matrix <- indicatorInsideGeneSetMatrix(
      superposition.rank = superposition.rank.exp,
      geneSet.position = geneSet.position,
      m = exp.m, n = exp.n
    )

    # （4）Extract the rank of gene set in each sample
    signature.temp.rank <- exp.rank * geneSet.position
    signature.temp.rank <- signature.temp.rank[-which(rowSums(signature.temp.rank) == 0), ]

    signature.rank <- apply(signature.temp.rank, 2, function(r) {
      rankByDesc(r, item.num = exp.m)
    })

    signature.rank <- sortMatrixByCol(signature.rank, set.decreasing = TRUE)

    # （5）Calculating ES score
    alpha <- 0.25
    score.for.oneset <- sapply(1:exp.n, function(i) {
      t4 <- indicatorInsideGeneSet.matrix[, i]
      t4[which(t4 != 0)] <- signature.rank[, i]
      stepCDFinGeneSet <- cumsum((abs(t4))^alpha) / sum((abs(signature.rank[, i]))^alpha)
      t3 <- indicatorInsideGeneSet.matrix[, i]
      stepCDFoutGeneSet <- cumsum(!t3) / sum(!t3)
      walkStat <- stepCDFinGeneSet - stepCDFoutGeneSet
      return(sum(walkStat))
    })
    return(score.for.oneset)
  })
  ssGSEA.score <- t(ssGSEA.score)
  colnames(ssGSEA.score) <- colnames(expressionProfile)
  return(ssGSEA.score)
}


#' Get rank of a matrix based on superposition by gradient.
#' Required for getting rank of elements in every column of a matrix.
#'
#' @param  raw.matrix A matrix consist of numeric values.
#' @param  m Numeric value indicating number of row of raw.matrix.
#' @param  n Numeric value indicating number of column of raw.matrix.
#'
#' @return rank of all values in the matrix

superpositionRank <- function(raw.matrix, m, n) {
  max.element <- max(raw.matrix)
  over.matrix <- matrix(rep(seq(0, max.element * (n - 1), by = max.element), each = m), nrow = m)
  superposition <- raw.matrix + over.matrix

  superposition.rank <- matrix(rank(superposition, ties.method = "first"), nrow = m)
  return(superposition.rank)
}



#' With the rank of all values in the matrix(superposition.rank), restore the rank
#' of elements in every column.
#'
#' @param  superposition.rank A matrix indicating rank of all values in the raw matrix.
#' @param  m Numeric value indicating number of row of matrix 'superposition.rank'.
#' @param  n Numeric value indicating number of column of matrix 'superposition.rank'.
#'
#' @return rank of elements in every column

rankMatrixByCol <- function(superposition.rank, m, n) {
  minus.matrix <- matrix(rep(seq(0, m * (n - 1), by = m), each = m), nrow = m)
  subtract.matrix <- superposition.rank - minus.matrix

  return(subtract.matrix)
}


#' Convert the rank of ascending order to descending order
#'
#' @param defult.rank The defult rank generated by the rank function
#' @param item.num Number of items used for rank
#'
#' @return rank of elements in descending order

rankByDesc <- function(defult.rank, item.num) {
  gap <- item.num - defult.rank

  desc.rank <- gap + 1

  return(desc.rank)
}


#' Sort every column of a matrix.
#'
#' @param  raw.matrix A matrix consist of numeric value.
#' @param  set.decreasing Logical, if true sort is decreasing, default by TRUE.

sortMatrixByCol <- function(raw.matrix, set.decreasing = TRUE) {
  if (is.null(dim(raw.matrix))) {
    subtract.matrix <- matrix(raw.matrix, nrow = 1)
  } else {
    n.num <- ncol(raw.matrix)
    m.num <- nrow(raw.matrix)

    over.matrix <- matrix(rep(seq(0, max(raw.matrix) * (n.num - 1), by = max(raw.matrix)), each = m.num), nrow = m.num)

    if (set.decreasing) {
      superposition <- raw.matrix - over.matrix
      superposition.sort <- sort(superposition, decreasing = set.decreasing)
      subtract.matrix <- superposition.sort + over.matrix
    } else {
      superposition <- raw.matrix + over.matrix
      superposition.sort <- sort(superposition, decreasing = set.decreasing)
      subtract.matrix <- superposition.sort - over.matrix
    }
  }
  return(subtract.matrix)
}




#' With the rank of all values in the matrix(superposition.rank),
#' get the matrix consist with 0 and 1, indicated the position of geneset,
#' required for calculating ES score of the geneset.
#'
#' @param  superposition.rank A matrix indicating rank of all values in the raw matrix.
#' @param  gSet.position A matrix consist of '0' and '1' show the position of signature
#' genes in expression profile, with same size of expression profile, '1' stands for
#' signature genes expression, '0' for other genes.
#' @param  m Numeric value indicating number of row of matrix 'superposition.rank'.
#' @param  n Numeric value indicating number of column of matrix 'superposition.rank'.
#'
#' @return

indicatorInsideGeneSetMatrix <- function(superposition.rank, geneSet.position, m, n) {
  indicatorFunInsideGeneSet <- numeric(length = m * n)

  indicatorFunInsideGeneSet[superposition.rank] <- geneSet.position
  indicatorFunInsideGeneSet <- matrix(indicatorFunInsideGeneSet, nrow = m)

  indicatorFunInsideGeneSet <- apply(indicatorFunInsideGeneSet, 2, rev)

  return(indicatorFunInsideGeneSet)
}
